modLoader="javafml"
loaderVersion="[42,)"
issueTrackerURL="https://www.github.com/xfacthd/framedblocks"
license="LGPL v3"

[[mods]]
modId="framedblocks"
version="${file.jarVersion}"
displayName="FramedBlocks"
#updateJSONURL="http://myurl.me/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/framedblocks"
logoFile="logo.png"
logoBlur=false
#credits="Thanks for this example mod goes to Java"
authors="XFactHD"
description='''
'''

[[dependencies.framedblocks]]
    modId="forge"
    mandatory=true
    versionRange="[43.1.55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.1,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="buildinggadgets"
    mandatory=false
    versionRange="[3.14.0,)"
    ordering="AFTER"
    side="BOTH"

#[[dependencies.framedblocks]]
#    modId="ctm"
#    mandatory=false
#    versionRange="[1.18-1.1.3+1,)"
#    ordering="AFTER"
#    side="CLIENT"

[[dependencies.framedblocks]]
    modId="diagonalfences"
    mandatory=false
    versionRange="[4.0.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.framedblocks]]
    modId="nocubes"
    mandatory=false
    versionRange="[1.19.1-0.5.0,)"
    ordering="NONE"
    side="CLIENT"
